# -*- coding: utf-8 -*-
"""Cópia de Python_Exercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeXAfHuiVVH4Ro9aOmGQDapUI_VopCMI

# **1 - Usando os recursos que vimos até agora, elabore um programa simples que faça os cálculos matemáticos básicos de 2 numeros. Exemplo: 2+2 ou 2/2 etc.**


a) o programa deve pedir ao usuário para digitar o nome completo e validar se ele digitou um nome completo para continua, senão abortar programa;

b) o programa deve exibir um menu com as opções matemáticas para o usuário escolher, em seguida pedir para digitar os 2 números (um de cada vez);

c) O programa deve exibir a resposta do cálculo com casas decimais e perguntar se o usuário deseja saír ou fazer um novo cálculo;

d) Caso o usuário saia em algum momento do programa, devemos agradecer chamando ele apenas pelo primeiro nome, o histórico dos cálculos que ele fez e a data hora que ele encerrou;

Dicas:

- print("") exibe texto;
- print("" + "") exibe concatenando textos;
- print("", "") exibe concatenando textos;
- variavelLista = list() cria uma variavel sendo uma lista editavel;
- try:  int(variavelX) força uma variável a se tornar um inteiro;
- except ValueError: executa algo que queira se o try falhou com erro
- float usado para números decimais;
- from datetime import datetime importa biblioteca para usar data e hora;
- input("Digite um valor") cria um campo para o usuário digitar algo e armazena;
- def cria uma função para retornar algum valor ou executar algo;
- nomeDaFuncao() chama uma função;
- if, elif, else: usado para condições e verificação de valores;
- return encerra um if ou uma função;
- [print(conteudo) for conteudo in variavelLista] exibe percorrendo uma lista;
- .clear limpa uma lista
- .insert(x,y) insere um valor em uma posição de uma lista
- global nomeVariavel cria uma variavel para ser usada em todo o programa;
- variavel.lower() mostra em minúscula
- variavel.upper() mostra em maiúscula
- variavel.split() recorta string ou lista em partes de acordo com parâmetro;
- nomeLista[3] retorna o conteúdo da posição 4 da lista (indice 3)
- datetime.today() retorna a data e hora em formato americano
"""

from datetime import datetime

def validar_nome_completo():
    nome_completo = input("Digite seu nome completo: ")
    if len(nome_completo.split()) < 2:
        print("Por favor, digite um nome completo.")
        return False, ""
    else:
        return True, nome_completo.split()[0]

def realizar_operacao(operacao, num1, num2):
    if operacao == 1:
        return num1 + num2
    elif operacao == 2:
        return num1 - num2
    elif operacao == 3:
        return num1 * num2
    elif operacao == 4:
        return num1 / num2

def main():
    valido, primeiro_nome = validar_nome_completo()
    if not valido:
        return

    historico_calculos = []
    continuar = True

    while continuar:
        print("\nOpções de operações:")
        print("1. Soma")
        print("2. Subtração")
        print("3. Multiplicação")
        print("4. Divisão")

        try:
            escolha = int(input("Escolha uma operação (1/2/3/4): "))
            if escolha < 1 or escolha > 4:
                print("Opção inválida. Por favor, escolha uma opção válida.")
                continue
        except ValueError:
            print("Por favor, digite um número válido.")
            continue

        num1 = float(input("Digite o primeiro número: "))
        num2 = float(input("Digite o segundo número: "))

        resultado = realizar_operacao